### ISSUE TITLE
Create initial API routes to support front-end

### ISSUE THREAD

**Issue by francisli** [sfbrigade/bats-server#18]
Link to the current front-end design: https://www.figma.com/file/5FQp0yeFrJOCR4DapnLUG3/Ambulance-Destination-Tool?node-id=0%3A1

**Comment by julianmclain** [comment]
After reviewing the current design, it looks like we have the following needs. @komerela let me know what you think after spending some time reviewing it as well.

EMS ringdown form API requirements:
- POST  /patient
- POST  /emergencyMedicalServiceCall
- POST  /patientDelivery
- PATCH /patientDelivery (so the UI can update the arrival time and admission time)
- GET   /hospitals (for populating the form select options)

@francisli I listed the /patient and /emergencyMedicalServiceCall routes in order to create the associated models for the `PatientDelivery` model. Instead of making 3 calls to the network when saving the form, do you think we should have a single route that saves all 3 models to the DB in 1 transaction?

EMS hospital info API requirements:
- @francisli we discussed that the ER statuses (i.e. bed count) would be provided by a web socket connection to the client. I haven't worked with web sockets before, so I'm happy to do some research and take a stab at what the implementation could look like or follow your lead on this one. LMK what you think.

**Comment by francisli** [comment]
I would definitely consider a single API call for the form save action. I.e. POST /ringdown or something-...

For the ER side, even if we decide to do a websocket connection, it's always good to have corresponding REST API fallbacks. The client could even use both- REST API calls to send/create info (client to server), and the websocket purely for notification/updates (server to client).

There are a couple of ways we could go for Websockets... one is to just use a very minimal Websocket library:

https://github.com/websockets/ws

Or, we could use a third-party library that adds some additional functionality on top, i.e:

https://www.npmjs.com/package/socket.io

**Comment by julianmclain** [comment]
@francisli Ok sounds good. Let's start with the REST API and then add in the websocket connection. Based on your feedback and some additional thought, I think the EMS side will need:

POST /ringdown
PATCH /patientDelivery (for updating arrival time and admission time)
GET /hospitalStatuses (for displaying ER bed count and other info)

Let me know what you think. If that looks good I can get started on the integration tests.

**Comment by komerela** [comment]
> After reviewing the current design, it looks like we have the following needs. @komerela let me know what you think after spending some time reviewing it as well.
> 
> EMS ringdown form API requirements:
> 
> * POST  /patient
> * POST  /emergencyMedicalServiceCall
> * POST  /patientDelivery
> * PATCH /patientDelivery (so the UI can update the arrival time and admission time)
> * GET   /hospitals (for populating the form select options)
> 
> @francisli I listed the /patient and /emergencyMedicalServiceCall routes in order to create the associated models for the `PatientDelivery` model. Instead of making 3 calls to the network when saving the form, do you think we should have a single route that saves all 3 models to the DB in 1 transaction?
> 
> EMS hospital info API requirements:
> 
> * @francisli we discussed that the ER statuses (i.e. bed count) would be provided by a web socket connection to the client. I haven't worked with web sockets before, so I'm happy to do some research and take a stab at what the implementation could look like or follow your lead on this one. LMK what you think.

@julianmclain Will this mean that data entry into the forms will happen back to back then post once rather than the 3 of them posting separately?

**Comment by julianmclain** [comment]
@komerela That was my original thought, but I think it will be better to consolidate everything into a single POST. It's more straightforward and minimizes the number of roundtrips over the network.

**Comment by julianmclain** [comment]
Hey @francisli - here's my latest thought on the routes needed. If it looks like a decent start I'll work on the integration tests for next week.
```
EMS side:
- POST   /ringdown
- PATCH  /ringdown
- GET    /hospitalstatuses

ER side:
- GET    /ringdowns
- POST   /hospitalstatus
```

On the ER side, I'm thinking the GET /ringdowns results can be filtered to a single hospital using a query param e.g. ?hospital={hospitalName}.

**Comment by francisli** [comment]
@julianmclain I think that sounds good...!
